# Generated by Django 4.1 on 2024-04-23 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_pupil_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Samaarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Qorajalpogiston', 'Qoraqalpogiston'), ('Qashqadaryo', 'Qashqadaryo'), ('Xorazm', 'Xorazm'), ('Surhandaryo', 'Surhandaryo'), ('Sirdaryo', 'Sirdaryo'), ('Namangan', 'Namangan'), ('Toshkent_shahar', 'Toshkent_shahar')], default='Toshkent_shahar', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rooms', to='common.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupils', to='common.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_director', to=settings.AUTH_USER_MODEL, verbose_name='Director'),
        ),
    ]
